services:
  - type: web
    name: notecraft-pro-api
    env: python
    region: oregon
    plan: starter
    buildCommand: |
      cd api && pip install -r requirements.txt
    startCommand: |
      cd api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODEL_REPO
        value: google/flan-t5-small
      - key: API_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: /opt/render/project/src/api